window.frases = [
  { t: "Cuando una puerta de felicidad se cierra, otra se abre; pero muchas veces miramos tanto la cerrada que no vemos la abierta.", a: "Helen Keller" },
  { t: "Arriesgarse es perder momentáneamente el equilibrio; no arriesgarse es perderlo para siempre.", a: "Søren Kierkegaard" },
  { t: "Amar a alguien significa verle el rostro tal como lo soñó Dios.", a: "Fiódor Dostoyevski" },
  { t: "Cada error es una clase pagada; no repitas el curso gratis.", a: "Anónimo" },
  { t: "Mejor es el fin de una cosa que su principio; mejor la paciencia que la soberbia.", a: "Proverbio hebreo" },
  { t: "Se puede resistir al ejército invasor, pero no a las ideas cuyo momento ha llegado.", a: "Simón Bolívar" },
  { t: "Cambiar el mundo, compañera san, que es la única manera de conservarlo.", a: "Mercedes Sosa" },
  { t: "El que comete un error y no lo corrige, comete otro error.", a: "Confucio" },
  { t: "Solo cuando talles el último árbol comprenderás que no se puede comer dinero.", a: "Proverbio cree" },
  { t: "Cuando veas a alguien bueno, piensa en imitarlo; cuando veas a alguien malo, examina tus propias faltas.", a: "Confucio" },
  { t: "La felicidad de tu vida depende de la calidad de tus pensamientos.", a: "Marco Aurelio" },
  { t: "No puedes volver atrás y empezar de nuevo, pero puedes empezar ahora y hacer un nuevo final.", a: "C. S. Lewis" },
  { t: "Lo que uno puede imaginar, otro lo puede crear; y quien sueña, ya empezó.", a: "Julio Verne" },
  { t: "El que lee mucho y anda mucho, ve mucho y sabe mucho.", a: "Miguel de Cervantes" },
  { t: "El comienzo es la parte más importante del trabajo.", a: "Platón" },
  { t: "No hay mal que dure cien años ni cuerpo que lo resista: todo pasa.", a: "Dicho popular" },
  { t: "La mejor hora para plantar un árbol fue hace veinte años; la segunda mejor hora es ahora.", a: "Proverbio chino" },
  { t: "Los dos días más importantes de tu vida son el día que naces y el día en que descubres por qué.", a: "Mark Twain" },
  { t: "Donde no hay amor, pon amor, y encontrarás amor.", a: "San Juan de la Cruz" },
  { t: "Parece siempre imposible hasta que se hace.", a: "Nelson Mandela" },
  { t: "Cada atardecer es prueba de que terminar también puede ser hermoso.", a: "Anónimo" },
  { t: "Nuestro mayor defecto está en rendirnos; el modo más seguro de salir adelante es intentarlo una vez más.", a: "Thomas Edison" },
  { t: "Si quieres ser feliz, sélo.", a: "León Tolstói" },
  { t: "Se aprende a vivir aprendiendo a dar.", a: "Mario Benedetti" },
  { t: "No cuentes los días: haz que los días cuenten.", a: "Anónimo" },
  { t: "¿Cuántos de nosotros estaríamos contentos de haber vivido como Anne Frank, escribiendo luz desde el sótano?", a: "Anónimo" },
  { t: "Los que entregan su libertad a cambio de seguridad no merecen ni libertad ni seguridad.", a: "Benjamin Franklin" },
  { t: "Y fue por ese río que llegó a mi vida el ruido del mar.", a: "Pablo Neruda" },
  { t: "El río no bebe su propia agua; el árbol no come su propia fruta: vivimos dándonos unos a otros.", a: "Proverbio africano" },
  { t: "Caminante, no hay camino: se hace camino al andar.", a: "Antonio Machado" },
  { t: "Sube conmigo, amor americano.", a: "Pablo Neruda" },
  { t: "Anoche perdí el mundo y gané el universo.", a: "Rumi" },
  { t: "La nieve cubre los campos, pero no esconde el camino del que sabe leer las estrellas.", a: "Proverbio nórdico" },
  { t: "Elige un trabajo que ames y no tendrás que trabajar ni un día en tu vida.", a: "Confucio" },
  { t: "Vencerse a sí mismo es victoria mayor que vencer mil veces a mil hombres.", a: "Buda" },
  { t: "Una flor no compite con la flor vecina; simplemente florece.", a: "Proverbio japonés" },
  { t: "La medida última de una persona no es dónde se para en los momentos de comodidad, sino dónde se para en los desafíos.", a: "Martin Luther King" },
  { t: "Cada uno de mis libros me ha enseñado algo nuevo, y sobre todo, me ha enseñado lo que yo ignoraba.", a: "Julio Cortázar" },
  { t: "Todo lo que hagas, hazlo con todo tu corazón, o no lo hagas en absoluto.", a: "Confucio" },
  { t: "Los recuerdos son del corazón; las palabras, solo del papel.", a: "Gabriel García Márquez" },
  { t: "El viento contrario también sostiene al ave que sabe inclinarse.", a: "Anónimo" },
  { t: "La belleza salvará al mundo si aprendemos a reconocerla en lo cotidiano.", a: "Fiódor Dostoyevski" },
  { t: "Primero decide quién quieres ser; después, haz lo que debas hacer.", a: "Epicteto" },
  { t: "Vivir es lo más raro del mundo; la mayoría de la gente apenas existe.", a: "Oscar Wilde" },
  { t: "Sé curioso sobre ellos, no sobre sus juicios; mantente siempre con la cara alegre hacia la luz.", a: "Walt Whitman" },
  { t: "Para ser irremplazable, uno debe ser siempre diferente.", a: "Coco Chanel" },
  { t: "Un hombre se convierte en lo que sueña cuando hace de su camino su casa.", a: "Antoine de Saint-Exupéry" },
  { t: "Todo cambia, y lo que hoy parece final es apenas un giro del camino.", a: "Mercedes Sosa" },
  { t: "Andar es la mejor manera de conversar con el mundo.", a: "Julio Cortázar" },
  { t: "Cuando manejas a trescientos kilómetros por hora, la lluvia parece sólida; así son los sueños cuando los persigues a fondo.", a: "Ayrton Senna" },
  { t: "La diligencia es madre de la buena ventura.", a: "Miguel de Cervantes" },
  { t: "Mejor hazlo imperfecto hoy que perfecto jamás.", a: "Winston Churchill" },
  { t: "Haz tu trabajo y luego da un paso atrás: es el único camino a la serenidad.", a: "Lao Tsé" },
  { t: "El alma se tiñe del color de sus pensamientos.", a: "Marco Aurelio" },
  { t: "Ser o no ser: esa es la pregunta. Decidir es el primer acto de libertad.", a: "William Shakespeare" },
  { t: "Lo que se opone al camino se convierte en el camino.", a: "Marco Aurelio" },
  { t: "Lo que demuestras hoy con calma será creído mañana por todos.", a: "Henry David Thoreau" },
  { t: "El miedo avisa; el valor decide; la acción transforma.", a: "Anónimo" },
  { t: "Sé paciente contigo: nada bueno crece apresurado, ni el trigo ni el alma.", a: "Anónimo" },
  { t: "Todas las ambiciones humanas son hermosas cuando llevan semillas de nobleza.", a: "Alexandre Dumas" },
  { t: "Al mar no se le pregunta adónde va: se aprende a navegar con él.", a: "Dicho popular" },
  { t: "La riqueza no consiste en tener mucho, sino en desear poco.", a: "Epicteto" },
  { t: "Es imposible aprender aquello que uno cree que ya sabe.", a: "Epicteto" },
  { t: "Hoy vence a ti mismo de ayer; mañana vence al más fuerte.", a: "Miyamoto Musashi" },
  { t: "El que persevera alcanza; el que insiste aprende dos veces.", a: "Dicho popular" },
  { t: "No compares tu capítulo uno con el capítulo veinte de otro.", a: "Anónimo" },
  { t: "Genio: uno por ciento inspiración y noventa y nueve por ciento transpiración.", a: "Thomas Edison" },
  { t: "El secreto de una buena vejez es un pacto honesto con la soledad y una pasión que no envejece.", a: "Gabriel García Márquez" },
  { t: "Recuerda que no obtener lo que quieres es a veces un golpe de suerte maravilloso.", a: "Dalai Lama" },
  { t: "El que da a los pobres no se empobrece; siembra en terreno que nunca falla.", a: "Proverbio árabe" },
  { t: "No esperes a sentirte listo: la preparación ocurre mientras caminas.", a: "Anónimo" },
  { t: "Incluso la noche más oscura terminará y el sol saldrá de nuevo.", a: "Victor Hugo" },
  { t: "Lo que no te mata te hace más fuerte.", a: "Friedrich Nietzsche" },
  { t: "El secreto del cambio es concentrar toda tu energía no en luchar contra lo viejo, sino en construir lo nuevo.", a: "Sócrates" },
  { t: "No le temas al hombre que practica diez mil golpes distintos; teme al que practica un golpe diez mil veces.", a: "Bruce Lee" },
  { t: "La compasión y la tolerancia no son signos de debilidad, sino de fuerza.", a: "Dalai Lama" },
  { t: "Nadie necesita esperar ni un momento para empezar a mejorar el mundo: es maravilloso cuánto puede hacerse.", a: "Anne Frank" },
  { t: "Un hombre con una idea nueva es un loco hasta que la idea triunfa.", a: "Mark Twain" },
  { t: "Tu tiempo es limitado, así que no lo gastes viviendo la vida de otro.", a: "Steve Jobs" },
  { t: "Nada está perdido si se tiene el valor de proclamar que todo está perdido y hay que empezar de nuevo.", a: "Julio Cortázar" },
  { t: "Puedo escribir los versos más tristes esta noche. Escribir, por ejemplo: la noche está estrellada.", a: "Pablo Neruda" },
  { t: "Quien arregla su propia vela ilumina también el bote vecino.", a: "Anónimo" },
  { t: "Quien conoce a los demás es sabio; quien se conoce a sí mismo está despierto.", a: "Lao Tsé" },
  { t: "Ayer era listo y quería cambiar el mundo; hoy soy sabio y me cambio yo.", a: "Rumi" },
  { t: "No es pobre el que tiene poco, sino el que desea más.", a: "Séneca" },
  { t: "La esperanza es el sueño del hombre despierto.", a: "Aristóteles" },
  { t: "El que espera el momento perfecto pierde todos los momentos buenos.", a: "Anónimo" },
  { t: "Ven, ven, quienquiera que seas; aún así ven: el nuestro no es un convoy de desesperación.", a: "Rumi" },
  { t: "El agua es lo más blando de todas las cosas, pero vence a lo más duro.", a: "Lao Tsé" },
  { t: "Más vale pájaro en mano que aprender a construir nidos: primero asegura, después sueña.", a: "Dicho popular" },
  { t: "Lo que puedes hacer o sueñas poder hacer, empiezalo; la osadía lleva en sí misma genio y poder.", a: "Johann Wolfgang von Goethe" },
  { t: "Una marea alta comienza siempre bajo el nivel de todas las mareas bajas.", a: "Anónimo" },
  { t: "Lo difícil se hace en algún momento; lo imposible, un poco más tarde.", a: "Anónimo" },
  { t: "No juzgues a tu hermano hasta que hayas caminado una luna entera con sus pasos.", a: "Proverbio cherokee" },
  { t: "El ganado muere, la familia muere; solo la fama de las buenas obras nunca muere.", a: "Hávamál nórdico" },
  { t: "Primero piensa, segundo cree, tercero sueña, y finalmente atrévete.", a: "Walt Disney" },
  { t: "Yo me celebro y me canto a mí mismo; y todo lo que soy también lo eres tú.", a: "Walt Whitman" },
  { t: "Hay cosas más valiosas que la valentía: hay cosas que solo se aprenden perdonando.", a: "C. S. Lewis" },
  { t: "La verdadera generosidad hacia el futuro consiste en dar todo al presente.", a: "Albert Camus" },
  { t: "El guerrero que espera el momento perfecto nunca pelea.", a: "Anónimo" },
  { t: "Si vas atravesando el infierno, sigue avanzando.", a: "Winston Churchill" },
  { t: "El que pregunta es tonto cinco minutos; el que no pregunta, lo es toda la vida.", a: "Proverbio chino" },
  { t: "Nunca mires hacia abajo para comenzar una escalera; mira hacia arriba y sube.", a: "Henry David Thoreau" },
  { t: "El que quiere miel debe soportar las picaduras de las abejas.", a: "Proverbio árabe" },
  { t: "Cada día es una página nueva: escribe algo que valga ser releído.", a: "Anónimo" },
  { t: "Yo hice a mis hijos pobres para que mis hijos no fueran pobres de corazón. Los hice sencillos para ser grande.", a: "Gabriela Mistral" },
  { t: "Cada persona, cuando abre los ojos por la mañana, recibe una página nueva del mundo.", a: "Eduardo Galeano" },
  { t: "Sin esfuerzo no hay pez que salte a la orilla.", a: "Proverbio ruso" },
  { t: "El amor ha de saber esperar; casi siempre la prisa lo arruina todo.", a: "Gabriela Mistral" },
  { t: "Comienza de inmediato a vivir y cuenta cada día como una vida separada.", a: "Séneca" },
  { t: "Toda tu vida has estado esperando a ti mismo; no huyas más.", a: "Yalal ad-Din Rumi" },
  { t: "Sostén en tus manos solo esto: el momento presente.", a: "Buda" },
  { t: "Si quieres saber adónde vas, pregunta a quien ya volvió del camino.", a: "Proverbio africano" },
  { t: "Dime y lo olvido; enséñame y quizá recuerde; involúcrame y aprenderé.", a: "Benjamin Franklin" },
  { t: "Camarón que se duerme se lo lleva la corriente: mantente despierto ante tus sueños.", a: "Dicho popular" },
  { t: "Una puerta que no abrimos también es una respuesta; atrevete a girar la manilla.", a: "Franz Kafka" },
  { t: "El maestro muestra la puerta, pero debes ser tú quien la cruce.", a: "Proverbio chino" },
  { t: "Caer es permitido; levantarse es obligatorio. Y mientras haya vida, hay oportunidad.", a: "Nelson Mandela" },
  { t: "No te rindas, aún estás a tiempo de alcanzar y comenzar de nuevo.", a: "Mario Benedetti" },
  { t: "Cae siete veces, levántate ocho.", a: "Proverbio japonés" },
  { t: "Escribe en tu corazón que cada día es el mejor día del año.", a: "Ralph Waldo Emerson" },
  { t: "Ya sea que creas poder hacerlo o que creas que no puedes, en ambos casos tienes razón.", a: "Henry Ford" },
  { t: "El que no tiene valor para soñar despierto nunca verá cumplirse sus sueños dormido.", a: "Muhammad Ali" },
  { t: "La duda es uno de los nombres de la inteligencia.", a: "Jorge Luis Borges" },
  { t: "Quien tiene un porqué para vivir puede soportar casi cualquier cómo.", a: "Friedrich Nietzsche" },
  { t: "El mayor placer de la vida es hacer lo que la gente dice que no puedes.", a: "Alexandre Dumas" },
  { t: "Un viaje de mil leguas comienza siempre con un primer paso.", a: "Lao Tsé" },
  { t: "Al que madruga, la vida lo despierta con más horas de luz.", a: "Dicho popular chileno" },
  { t: "El invierno siempre encuentra en sí mismo una promesa secreta de primavera.", a: "Proverbio nórdico" },
  { t: "Una vida sin examen no merece ser vivida.", a: "Sócrates" },
  { t: "Aunque el mundo esté lleno de sufrimiento, también está lleno de la superación del sufrimiento.", a: "Helen Keller" },
  { t: "Solo los educados son libres.", a: "Epicteto" },
  { t: "El poeta es un pequeño dios que crea mundos con palabras aladas.", a: "Vicente Huidobro" },
  { t: "Canta lo que sientes y el mundo encontrará en tu voz lo que él mismo siente.", a: "Atahualpa Yupanqui" },
  { t: "Ten siempre contigo un sueño imposible: mantiene viva la parte de ti que aún puede creer.", a: "Oscar Wilde" },
  { t: "Escucha el murmullo del agua y aprenderás que la fuerza puede ser suave.", a: "Proverbio nativo americano" },
  { t: "Cada vez que te enseña algo, el mundo se vuelve un poco menos desconocido.", a: "Lewis Carroll" },
  { t: "Si buscas tranquilidad, haz menos cosas, pero hazlas mejor.", a: "Marco Aurelio" },
  { t: "No tenemos dos vidas: una para aprender y otra para aplicar lo aprendido. Solo hay una.", a: "Séneca" },
  { t: "Ve hasta donde puedas; cuando llegues allí, verás más lejos.", a: "Thomas Carlyle" },
  { t: "La espada gana batallas; el carácter gana vidas.", a: "Proverbio japonés" },
  { t: "Empieza donde estás, con lo que tienes, y el camino aparecerá bajo tus pasos.", a: "Anónimo" },
  { t: "En pleno invierno descubrí en mí un invencible verano.", a: "Albert Camus" },
  { t: "El éxito no es cuestión de talento sino de pasión y constancia.", a: "Pelé" },
  { t: "Todo lo que tenemos que decidir es qué hacer con el tiempo que se nos ha dado.", a: "J. R. R. Tolkien" },
  { t: "Sé tú mismo; los demás puestos ya están tomados.", a: "Oscar Wilde" },
  { t: "Sé agua, amigo mío: vacía tu mente, sé formalessino como el agua.", a: "Bruce Lee" },
  { t: "La vida es breve; el arte, largo; la oportunidad, fugaz; la experiencia, engañosa; el juicio, difícil.", a: "Horacio" },
  { t: "La mejor manera de animarte a ti mismo es intentar animar a alguien más.", a: "Mark Twain" },
  { t: "Guarda tu naturaleza salvaje: ella es tu raíz más honda y tu mejor brújula.", a: "Walt Whitman" },
  { t: "No hay nada más fuerte que quienes convierten su herida en luz para otros.", a: "Fiódor Dostoyevski" },
  { t: "Pies, ¿para qué los quiero si tengo alas para volcar?", a: "Frida Kahlo" },
  { t: "Aprende de las reglas como un experto, pero vívelas como un artista.", a: "Dalai Lama" },
  { t: "La memoria es del corazón, y el olvido también; pero la esperanza es del pueblo entero.", a: "Eduardo Galeano" },
  { t: "Muy poco se necesita para una vida feliz; todo está dentro de ti, en tu manera de pensar.", a: "Marco Aurelio" },
  { t: "La sabiduría está en el asombro; quien deja de asombrarse, envejece.", a: "Octavio Paz" },
  { t: "No todo lo que es oro brilla, ni todos los que vagan están perdidos.", a: "J. R. R. Tolkien" },
  { t: "El sol calienta a todos por igual, pero nadie quema su casa para asar su pan.", a: "Proverbio árabe" },
  { t: "Un gramo de acción vale más que una tonelada de intenciones.", a: "Benjamin Franklin" },
  { t: "Una pasión compartida multiplica la fuerza de quien la sostiene.", a: "Antonio Skármeta" },
  { t: "No temas a la grandeza: algunos nacen grandes, otros la alcanzan y otros la buscan cada día.", a: "William Shakespeare" },
  { t: "El visionario susurra ideas al viento; el sabio las planta en tierra firme.", a: "Proverbio japonés" },
  { t: "El futuro pertenece a quienes creen en la belleza de sus sueños.", a: "Eleanor Roosevelt" },
  { t: "La única manera de hacer un gran trabajo es amar lo que haces; si aún no lo encontraste, sigue buscando.", a: "Steve Jobs" },
  { t: "Que tu camino siga al sol naciente hasta que el cansancio te encuentre sonriendo.", a: "Bendición irlandesa" },
  { t: "Flota como mariposa, pica como abeja: cada golpe debe tener propósito detrás.", a: "Muhammad Ali" },
  { t: "La única manera de tener un amigo es siendo uno.", a: "Ralph Waldo Emerson" },
  { t: "Aprende a descansar, no a rendirte.", a: "Anónimo" },
  { t: "Donde pongas tu atención, ahí pondrás también tu vida.", a: "Anónimo" },
  { t: "Cree en ti mismo y ya vas por la mitad del camino.", a: "Theodore Roosevelt" },
  { t: "No importa lo que hayas hecho; lo importante es hacia dónde vas ahora.", a: "Martin Luther King" },
  { t: "Cuida tus pensamientos porque se harán palabras; cuida tus palabras porque se harán actos.", a: "Lao Tsé" },
  { t: "Lo que la mano hace en secreto, el alma lo sabe a gritos.", a: "Gabriela Mistral" },
  { t: "La disciplina elegida se siente como libertad; la impuesta, como cadena.", a: "Anónimo" },
  { t: "En las desdichas se conoce al amigo verdadero.", a: "Francisco de Quevedo" },
  { t: "Cuando bebas agua recuerda quién trajo la lluvia; gratitud es memoria del corazón.", a: "Proverbio nativo americano" },
  { t: "Lo esencial es invisible a los ojos; mira con el corazón.", a: "Antoine de Saint-Exupéry" },
  { t: "Todos tus sueños pueden hacerse realidad si tienes el coraje de perseguirlos.", a: "Walt Disney" },
  { t: "No hay dolor que dure, ni pena que no se cure cantando.", a: "Violeta Parra" },
  { t: "Sabio es quien conoce los medios necesarios en cada caso.", a: "Johann Wolfgang von Goethe" },
  { t: "Somos hechos de la misma materia que los sueños.", a: "William Shakespeare" },
  { t: "Si cada uno barre delante de su puerta, todo el pueblo estará limpio.", a: "Proverbio alemán" },
  { t: "No es porque las cosas sean difíciles que no nos atrevemos; es porque no nos atrevemos que son difíciles.", a: "Séneca" },
  { t: "Nunca dejes que la escuela interfiera con tu educación.", a: "Mark Twain" },
  { t: "Somos vecinos de nuestros sueños cuando trabajamos junto a ellos.", a: "Anónimo" },
  { t: "La vida sin fiesta es un largo camino sin fuentes.", a: "Proverbio griego" },
  { t: "La vida es como andar en bicicleta: para mantener el equilibrio, debes seguir moviéndote.", a: "Albert Einstein" },
  { t: "La manera de empezar es dejar de hablar y comenzar a hacer.", a: "Walt Disney" },
  { t: "La constancia convierte lo extraordinario en rutina posible.", a: "Anónimo" },
  { t: "Debes subir la montaña sabiendo que la cima te hará ver otras montañas.", a: "Proverbio chino" },
  { t: "Tu único límite real es el que aceptas sin discutir.", a: "Anónimo" },
  { t: "La fuerza no viene de la capacidad física, sino de una voluntad indomable.", a: "Mahatma Gandhi" },
  { t: "Amor es la palabra más malgastada y la más necesitada para hacer valer la vida.", a: "Octavio Paz" },
  { t: "No son las cosas las que perturban a las personas, sino sus opiniones sobre ellas.", a: "Epicteto" },
  { t: "Yo no soy el más apto, pero me quedo más tiempo martillando la misma piedra.", a: "Abraham Lincoln" },
  { t: "El éxito no es final; el fracaso no es fatal: lo que cuenta es el coraje de continuar.", a: "Winston Churchill" },
  { t: "Locura es hacer siempre lo mismo y esperar resultados distintos.", a: "Albert Einstein" },
  { t: "La paz empieza con una sonrisa.", a: "Madre Teresa" },
  { t: "Todo lo que somos es resultado de lo que hemos pensado.", a: "Buda" },
  { t: "El hombre que tiene un porqué vive con paciencia cualquier destino.", a: "Fiódor Dostoyevski" },
  { t: "La oscuridad no puede expulsar a la oscuridad; solo la luz puede hacerlo.", a: "Martin Luther King" },
  { t: "Mantente hambriento; mantente necio; mantente despierto ante tu propia vida.", a: "Steve Jobs" },
  { t: "El secreto de salir adelante es comenzar.", a: "Mark Twain" },
  { t: "Sonríe: es el idioma más corto entre dos desconocidos.", a: "Anónimo" },
  { t: "Los primeros en disculparse son los más valientes.", a: "Platón" },
  { t: "Lo bueno, si breve, dos veces bueno.", a: "Baltasar Gracián" },
  { t: "La paz viene de dentro; no la busques fuera.", a: "Buda" },
  { t: "Un día sin intentar nada nuevo es un día que el calendario guarda en gris.", a: "Anónimo" },
  { t: "Sola podemos hacer tan poco; juntas podemos hacer tanto.", a: "Helen Keller" },
  { t: "No hay pasión por encontrar en una vida fácil; la gloria nace de vencer lo difícil.", a: "Nelson Mandela" },
  { t: "Dame seis horas para cortar un árbol y pasaré las primeras cuatro afilando el hacha.", a: "Abraham Lincoln" },
  { t: "El pesajismo optimista espera que todo salga bien sin motivo; la esperanza trabaja para que salga bien.", a: "Winston Churchill" },
  { t: "Todo tiene su tiempo, y todo lo que se quiere debajo del cielo tiene su hora.", a: "Eclesiastés" },
  { t: "Lo mejor del futuro es que llega un día a la vez.", a: "Abraham Lincoln" },
  { t: "Que tus hijos sean como flechas vivas lanzadas hacia un mañana luminoso.", a: "Jalil Gibran" },
  { t: "Despacio respiro, despacio camino; pero siempre adelante.", a: "Mario Benedetti" },
  { t: "Hoy es el alumno de ayer; mañana será maestro de alguien.", a: "Proverbio japonés" },
  { t: "Un buen amigo vale más que cien parientes lejanos.", a: "Proverbio irlandés" },
  { t: "La inspiración llega cuando menos la buscas, pero solo visita a quien trabaja.", a: "Gustavo Adolfo Bécquer" },
  { t: "Ni siquiera el más sabio puede ver todos los caminos que se abren ante tus pies.", a: "J. R. R. Tolkien" },
  { t: "Odio cada minuto de entrenamiento, pero me dije: no renuncies; sufre ahora y vive el resto de tu vida como campeón.", a: "Muhammad Ali" },
  { t: "Somos lo que hacemos repetidamente; la excelencia, entonces, no es un acto, sino un hábito.", a: "Aristóteles" },
  { t: "La sabiduría nos llega cuando ya no nos sirve de nada.", a: "Gabriel García Márquez" },
  { t: "Con paciencia se cruza el océano paso a paso.", a: "Proverbio griego" },
  { t: "Mientras posponemos la vida, esta pasa.", a: "Séneca" },
  { t: "A quienes les parecía que bailábamos locos, era porque no podían escuchar la música.", a: "Friedrich Nietzsche" },
  { t: "El ojo del amo engorda al caballo: cuida lo tuyo y crecerá.", a: "Proverbio ruso" },
  { t: "En medio del invierno aprendí por fin que había en mí un sol inagotable.", a: "Albert Camus" },
  { t: "Un poco de fragancia siempre queda en las manos de quien da flores.", a: "Jalil Gibran" },
  { t: "Las gotas de agua tallan la piedra no por fuerza, sino por caer con frecuencia.", a: "Ovidio" },
  { t: "Escribe tu vida con la tinta del coraje; los capítulos tristes también hacen grandes historias.", a: "Isabel Allende" },
  { t: "Todo experto fue alguna vez un principiante que no se rindió.", a: "Anónimo" },
  { t: "Cuanto más te celebras por lo que no tienes, menos disfrutas lo que sí tienes.", a: "Oprah Winfrey" },
  { t: "Tienes poder sobre tu mente, no sobre los acontecimientos externos. Comprende esto y hallarás fuerza.", a: "Marco Aurelio" },
  { t: "Lo importante es que nunca te acostumbres a la injusticia: la costumbre es la primera muerte del alma.", a: "Antonio Skármeta" },
  { t: "Nadie puede hacerte sentir inferior sin tu consentimiento.", a: "Eleanor Roosevelt" },
  { t: "Pequeños pasos diarios valen más que grandes saltos ocasionales.", a: "Anónimo" },
  { t: "La felicidad es amor; nada más. Es feliz quien ama, quien trabaja y quien comparte.", a: "Hermann Hesse" },
  { t: "Tu tarea no es buscar el amor, sino encontrar las barreras que tú mismo construiste contra él.", a: "Yalal ad-Din Rumi" },
  { t: "Hay solo dos días en el año en que nada se puede hacer: uno se llama ayer y otro mañana.", a: "Dalai Lama" },
  { t: "Los mejores y más hermosos cosas del mundo no pueden verse ni tocarse: deben sentirse con el corazón.", a: "Helen Keller" },
  { t: "Querer es poder cuando el querer camina.", a: "Proverbio latino" },
  { t: "Las estrellas no se apagan por la noche; solo esperan ojos que busquen.", a: "Anónimo" },
  { t: "Ser segundo es ser el primero de los perdedores; pero perder enseñando es ganar para siempre.", a: "Ayrton Senna" },
  { t: "Despacio se va lejos cuando la dirección es buena.", a: "Proverbio ruso" },
  { t: "La revolución comienza siempre con una palabra dicha a tiempo y con amor.", a: "Ernesto Cardenal" },
  { t: "Arriba con el rostro lavado de aurora quien luchó por la alegría.", a: "Pablo Neruda" },
  { t: "La sabiduría de la vida consiste en eliminar lo que no importa.", a: "Antón Chéjov" },
  { t: "No hay escuela igual a la casa, ni maestro como la madre.", a: "Gabriela Mistral" },
  { t: "Hoy todavía tiene espacio para convertirse en tu día favorito.", a: "Anónimo" },
  { t: "A donde el corazón va, el pie llega aunque tarde.", a: "Dicho popular" },
  { t: "La vida solo puede ser comprendida mirando hacia atrás, pero debe ser vivida mirando hacia adelante.", a: "Søren Kierkegaard" },
  { t: "Seamos realistas: exijamos lo imposible. La imaginación al poder.", a: "Frida Kahlo" },
  { t: "El precio de cualquier cosa es la cantidad de vida que cambias por ella.", a: "Henry David Thoreau" },
  { t: "Un viaje de mil leguas también se recorre paso a paso: el sabio no se apresura, avanza.", a: "Proverbio chino" },
  { t: "No busques luz afuera cuando puedes encender una dentro.", a: "Anónimo" },
  { t: "Sé el cambio que quieres ver en el mundo.", a: "Mahatma Gandhi" },
  { t: "Todos Felices los que creen; más felices los que construyen lo que creen.", a: "León Tolstói" },
  { t: "La educación es el arma más poderosa que puedes usar para cambiar el mundo.", a: "Nelson Mandela" },
  { t: "La paciencia es el árbol de raíz amarga pero de frutos muy dulces.", a: "Proverbio persa" },
  { t: "Vive como si fueras a morir mañana; aprende como si fueras a vivir siempre.", a: "Mahatma Gandhi" },
  { t: "Primero te ignoran, luego se ríen, luego pelean; entonces ganas.", a: "Mahatma Gandhi" },
  { t: "Hay que correr tan rápido como puedas para quedarse en el mismo lugar; para llegar a otra parte hay que correr el doble.", a: "Lewis Carroll" },
  { t: "Yo solo sé que no sé nada.", a: "Sócrates" },
  { t: "La paz interior comienza el momento en que decides no dejar que otra persona o evento controle tus emociones.", a: "Dalai Lama" },
  { t: "Mientras respiro, espero.", a: "Proverbio latino" },
  { t: "Ningún río regresa a su fuente, pero todos encuentran el mar.", a: "Proverbio japonés" },
  { t: "Está prohibido rendirse, prohibido perder la fe, prohibido caminar sin alegría.", a: "Eduardo Galeano" },
  { t: "La suerte es lo que sucede cuando la preparación encuentra la oportunidad.", a: "Séneca" },
  { t: "Empieza pequeño, empieza torpe, pero empieza hoy.", a: "Anónimo" },
  { t: "Cuando el viento sopla fuerte, los árboles débiles aprenden a bailar.", a: "Dicho popular" },
  { t: "La simplicidad es la máxima elegancia; quita todo lo innecesario y quedará lo esencial.", a: "Coco Chanel" },
  { t: "No hay nada fuera de ti mismo que pueda darte poder.", a: "Miyamoto Musashi" },
  { t: "Deja que tus logros hablen despacio y largo tiempo.", a: "Anónimo" },
  { t: "Los que dicen que algo no se puede hacer no deberían interrumpir a los que lo están haciendo.", a: "Proverbio chino" },
  { t: "Las olas no preguntan cuántas veces rompieron contra la roca: siguen llegando.", a: "Anónimo" },
  { t: "Si piensas que algo es imposible, lo harás imposible; si crees posible, ya empezaste.", a: "Bruce Lee" },
  { t: "Cualquier destino, por largo y complicado que sea, es en realidad una sola instantánea: el instante en que el hombre descubre quién es.", a: "Jorge Luis Borges" },
  { t: "Conoce a tu enemigo y conócete a ti mismo; en cien batallas no correrás peligro.", a: "Sun Tzu" },
  { t: "La marea que hoy parece contra ti es la misma agua que mañana te llevará a mar abierto.", a: "Anónimo" },
  { t: "Las palabras son como el viento; los hechos son como la montaña.", a: "Proverbio chino" },
  { t: "No vayas donde pueda llevarte un sendero; ve donde no haya ninguno y deja huella.", a: "Ralph Waldo Emerson" },
  { t: "Muchas manos pequeñas, trabajando juntas, mueven montañas enteras.", a: "Proverbio africano" },
  { t: "Todos piensan en cambiar el mundo, pero nadie piensa en cambiarse a sí mismo.", a: "León Tolstói" },
  { t: "Lo que la sangre calla, la voz lo canta; y cantar ya es empezar a sanar.", a: "Jaime Sabines" },
  { t: "Escribe las heridas en la arena y los favores en la piedra.", a: "Proverbio árabe" },
  { t: "Ve confiado en la dirección de tus sueños; vive la vida que imaginas.", a: "Henry David Thoreau" },
  { t: "El trabajo es amor hecho visible.", a: "Jalil Gibran" },
  { t: "Yo no he fracasado; simplemente encontré diez mil maneras que no funcionan.", a: "Thomas Edison" },
  { t: "Deja que las cosas fluyan como el agua: la fuerza no está en la rigidez sino en adaptarse sin romperse.", a: "Bruce Lee" },
  { t: "Mientras haya un corazón que sienta, habrá poesía que lo despierte.", a: "Gustavo Adolfo Bécquer" },
  { t: "Nuestra mayor gloria no es caer nunca, sino levantarnos cada vez que caemos.", a: "Confucio" },
  { t: "Lo que buscas te está buscando también.", a: "Rumi" },
  { t: "Todo lo que una persona imagina, otra puede hacerlo realidad.", a: "Julio Verne" },
  { t: "Sé fiel a ti mismo y no podrás engañar a nadie.", a: "Anónimo" },
  { t: "No hay nada escrito para nadie; el futuro es un territorio que se construye caminando.", a: "Gabriel García Márquez" },
  { t: "El silencio del amanecer guarda respuestas que el ruido del día desordena.", a: "Anónimo" },
  { t: "La fortuna favorece a los audaces.", a: "Virgilio" },
  { t: "La felicidad no es una meta, sino un método de viaje.", a: "Mario Benedetti" },
  { t: "Ser bueno es fácil; ser justo, eso sí es difícil.", a: "Victor Hugo" },
  { t: "Nada te turbe, nada te espante; todo se pasa, quien a Dios espera no le falta nada.", a: "Santa Teresa de Jesús" },
  { t: "No digas que eres incapaz: di todavía no puedo, y practica.", a: "Antón Chéjov" },
  { t: "Las palabras no están hechas para esconder los pensamientos, sino para mostrarlos.", a: "Nicanor Parra" },
  { t: "Un buen comienzo es la mitad del trabajo entero.", a: "Proverbio griego" },
  { t: "Aún hay esperanza mientras los corazones fieles laten juntos.", a: "J. R. R. Tolkien" },
  { t: "Los pueblos unidos jamás serán vencidos cuando su canto se levanta con dignidad.", a: "Víctor Jara" },
  { t: "No hay nada más hermoso que tener un sueño claro y la fuerza para perseguirlo.", a: "Frida Kahlo" },
  { t: "Vive de modo que tu presencia sume y tu ausencia duela poco.", a: "Anónimo" },
  { t: "Cuando bebas agua, recuerda la primavera.", a: "Proverbio sioux" },
  { t: "Tengo un sueño, y cada día que trabajo por él lo hago un poco más real.", a: "Martin Luther King" },
  { t: "Gota a gota, el agua talla no solo la piedra sino también el carácter.", a: "Proverbio latino" },
  { t: "Educar la mente sin educar el corazón no es educación en absoluto.", a: "Aristóteles" },
  { t: "El camino se construye andando, aunque empiece bajo tus propios pies dudosos.", a: "Franz Kafka" },
  { t: "El valiente no es quien no siente miedo, sino quien lo conquista.", a: "Nelson Mandela" },
  { t: "Piensa en toda la belleza que aún queda alrededor tuyo y alégrate.", a: "Anne Frank" },
  { t: "Gracias a la vida que me ha dado tanto: me dio la risa y me dio el llanto.", a: "Violeta Parra" },
  { t: "Para volar, no busques alas prestadas: cultiva tu propio viento.", a: "Antoine de Saint-Exupéry" },
  { t: "El que mueve una montaña comienza cargando piedras pequeñas.", a: "Confucio" },
  { t: "Entre el sueño y la acción hay puentes llamados decisiones.", a: "Yalal ad-Din Gibran" },
  { t: "La cultura no pertenece solo a los que tienen dinero; pertenece a todos.", a: "Víctor Jara" },
  { t: "Innovación distingue a un líder de un seguidor.", a: "Steve Jobs" },
  { t: "La duda hace vacilar a los cobardes y despierta a los valientes.", a: "William Shakespeare" },
  { t: "Todo pensamiento verdadero se realiza alguna día.", a: "León Tolstói" },
  { t: "Cuando estés sediento, cava tu propio pozo: el agua ajena nunca sabe igual.", a: "Proverbio japonés" },
  { t: "Yo te cuento este sueño para que tú lo continúes.", a: "Jorge Luis Borges" },
  { t: "El crédito pertenece al hombre que está realmente en la arena, cuyo rostro está marcado por el polvo y el sudor del esfuerzo.", a: "Theodore Roosevelt" },
  { t: "El futuro es algo que alcanza a quien cree en él antes de verlo.", a: "C. S. Lewis" },
  { t: "La imaginación es más importante que el conocimiento; abraza ambas.", a: "Albert Einstein" },
  { t: "Haz de tu vida un sueño, y de tu sueño una realidad.", a: "Antoine de Saint-Exupéry" },
  { t: "Lo que gastas no se pierde; lo que das con amor queda sembrado para siempre.", a: "Madre Teresa" },
  { t: "Despierta, porque tu estrella ya cruzó la mitad del cielo.", a: "Yalal ad-Din Rumi" },
  { t: "Nadie se baña dos veces en el mismo río.", a: "Heráclito" },
  { t: "Soy humano y nada de lo humano me resulta ajeno.", a: "Terencio" },
  { t: "Que cada uno haga lo suyo y vaya a lo suyo, que es el modo más seguro de llegar lejos.", a: "Baltasar Gracián" },
  { t: "La mente no es un recipiente por llenar, sino un fuego por encender.", a: "Plutarco" },
  { t: "Venir juntos es el comienzo; mantenerse juntos es el progreso; trabajar juntos es el éxito.", a: "Henry Ford" },
  { t: "La felicidad es cuando lo que piensas, lo que dices y lo que haces están en armonía.", a: "Mahatma Gandhi" },
  { t: "Lo que el pueblo necesita es alegría y canto.", a: "Violeta Parra" },
  { t: "Si no puedes volar, corre; si no puedes correr, camina; si no puedes caminar, gatea; pero sea lo que sea, sigue avanzando.", a: "Martin Luther King" },
  { t: "La libertad es un ejercicio cotidiano o deja de existir.", a: "Mario Benedetti" },
  { t: "Haz lo que puedas, con lo que tengas, donde estés.", a: "Theodore Roosevelt" },
  { t: "De todos los instrumentos, el más precioso es el libro, porque los demás son extensiones del cuerpo; el libro, de la imaginación y la memoria.", a: "Jorge Luis Borges" },
  { t: "La paciencia tiene más poder que la fuerza.", a: "Plutarco" },
  { t: "Nadie tan joven con un viejo error, ni tan viejo para un nuevo acierto.", a: "Proverbio irlandés" },
  { t: "Cada mañana nacemos de nuevo; lo que hacemos hoy es lo que más importa.", a: "Buda" },
  { t: "Amar es descubrir que el otro también tiene un mundo.", a: "Gabriela Mistral" },
  { t: "Al que madruga, el sol lo acompaña; al que camina, el camino lo enseña.", a: "Atahualpa Yupanqui" },
  { t: "Quien no ha buscado su propio camino repite siempre el camino ajeno.", a: "Rosario Castellanos" },
  { t: "Es tan corto el amor, y es tan largo el olvido.", a: "Pablo Neruda" },
  { t: "Solo el que piensa y siente al mismo tiempo puede cambiar el mundo.", a: "Octavio Paz" },
  { t: "Todo necio confunde valor y precio.", a: "Antonio Machado" },
  { t: "La vida es la única realidad que vale; todo lo demás es decoración.", a: "Frida Kahlo" },
  { t: "Hay que endurecerse, pero sin perder jamás la ternura.", a: "Antonio Machado" },
  { t: "Debes tener caos dentro de ti para dar a luz una estrella danzante.", a: "Friedrich Nietzsche" },
  { t: "La valentía consiste en conocer qué temer y qué no temer.", a: "Platón" },
  { t: "Hay dos maneras de ser feliz en este mundo: una es hacerse el tonto y la otra serlo.", a: "Nicanor Parra" },
  { t: "Trata de no volverte un hombre de éxito, sino más bien un hombre de valor.", a: "Albert Einstein" },
  { t: "Insiste en ti mismo; nunca imites.", a: "Ralph Waldo Emerson" },
  { t: "Ánimo, que las adversidades fueron puestas en el mundo para prueba de los varones esforzados.", a: "Miguel de Cervantes" },
  { t: "No podemos todos hacer grandes cosas, pero podemos hacer cosas pequeñas con gran amor.", a: "Madre Teresa" },
  { t: "La perseverancia es lo que convierte los sueños en realidad.", a: "Simón Bolívar" },
  { t: "Quien siembra vientos cosecha tormentas; quien siembra bien cosecha paz.", a: "Proverbio hebreo" },
  { t: "Para llegar lejos no importa la velocidad, sino la dirección constante.", a: "Anónimo" },
  { t: "Utopía está en el horizonte: camino dos pasos, ella se aleja dos pasos. Sirve para eso: para caminar.", a: "Eduardo Galeano" },
  { t: "En medio de la dificultad reside la oportunidad.", a: "Albert Einstein" },
];
// Frase especial para el Día Fuera del Tiempo (20 jun · víspera del We Tripantu) — no pertenece a ninguna luna
window.fraseDFT = { t: "Hoy el tiempo se detiene para que el alma respire. No es un día que se cuenta, es un día que se siente: cierra el ciclo con gratitud, suelta lo que ya no sirve y abre el corazón al nuevo sol.", a: "Día Fuera del Tiempo · 20 de junio · We Tripantu" };
window.fraseDelDia = function(i){ return window.frases[i % window.frases.length]; };
